(split) Fix compile errors with GCC 4.4.x and default headers
Starting with 4.4.x, GCC's C++ frontend does not include default headers
anymore. This leads to compile errors such as this one:

parser/rpp/pp-internal.h: In function ‘void rpp::_PP_internal::output_line(const
std::string&, int, _OutputIterator)’:
parser/rpp/pp-internal.h:75: error: there are no arguments to ‘snprintf’ that
depend on a template parameter, so a declaration of ‘snprintf’ must be available

Include <cstdio> explicitly in both generator/parser/rpp/pp-internal.h and
juic/javautils.cpp to fix the errors.

Signed-off-by: Francis Galiegue <fgaliegue@gmail.com>